In [2]:
import streamlit as st
import requests
import pandas as pd
import plotly.graph_objs as go

API_KEY = st.secrets["api"]["iex_key"]
API_BASE_URL = "https://cloud.iexapis.com/stable/"

def get_stock_data(symbol, time_range="1y"):
    params = {"token": API_KEY}
    response = requests.get(f"{API_BASE_URL}stock/{symbol}/chart/{time_range}", params=params)
    data = response.json()

    if "error" in data:
        st.error(f"Error: {data['error']}")
        return None

    stock_data = pd.DataFrame(data)
    stock_data["date"] = pd.to_datetime(stock_data["date"])
    stock_data.set_index("date", inplace=True)
    # stock_data = stock_data[["open", "high", "low", "close", "volume"]]
    # stock_data.columns = ["Open", "High", "Low", "Close", "Volume"]
    return stock_data

df = get_stock_data("AAPL", time_range="1y")
df.had()

,close,high,low,open,priceDate,symbol,volume,id,key,subkey,...,uLow,uVolume,fOpen,fClose,fHigh,fLow,fVolume,label,change,changePercent
date,,,,,,,,,,,,,,,,,,,,,
2023-05-10,173.56,174.03,171.90,173.02,2023-05-10,AAPL,53724501,HISTORICAL_PRICES,AAPL,,...,171.90,53724501,171.86,172.39,172.86,170.75,53724501,"May 10, 23",0.00,0.0000
2023-05-11,173.75,174.59,172.17,173.85,2023-05-11,AAPL,49514676,HISTORICAL_PRICES,AAPL,,...,172.17,49514676,172.69,172.59,173.42,171.02,49514676,"May 11, 23",0.19,0.0011
2023-05-12,172.57,174.06,171.00,173.62,2023-05-12,AAPL,45533138,HISTORICAL_PRICES,AAPL,,...,171.00,45533138,172.70,171.66,173.14,170.09,45533138,"May 12, 23",-1.18,-0.0068
2023-05-15,172.07,173.21,171.47,173.16,2023-05-15,AAPL,37266659,HISTORICAL_PRICES,AAPL,,...,171.47,37266659,172.24,171.16,172.29,170.56,37266659,"May 15, 23",-0.50,-0.0029
2023-05-16,172.07,173.14,171.80,171.99,2023-05-16,AAPL,42110293,HISTORICAL_PRICES,AAPL,,...,171.80,42110293,171.08,171.16,172.22,170.89,42110293,"May 16, 23",0.00,0.0000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 252 entries, 2023-05-10 to 2024-05-09
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   close                 252 non-null    float64
 1   high                  252 non-null    float64
 2   low                   252 non-null    float64
 3   open                  252 non-null    float64
 4   priceDate             252 non-null    object
 5   symbol                252 non-null    object
 6   volume                252 non-null    int64
 7   id                    252 non-null    object
 8   key                   252 non-null    object
 9   subkey                252 non-null    object
 10  updated               252 non-null    float64
 11  changeOverTime        252 non-null    float64
 12  marketChangeOverTime  252 non-null    float64
 13  uOpen                 252 non-null    float64
 14  uClose                252 non-null    float64
 15  uHigh                 252 non-null    float64
 16  uLow                  252 non-null    float64
 17  uVolume               252 non-null    int64
 18  fOpen                 252 non-null    float64
 19  fClose                252 non-null    float64
 20  fHigh                 252 non-null    float64
 21  fLow                  252 non-null    float64
 22  fVolume               252 non-null    int64
 23  label                 252 non-null    object
 24  change                252 non-null    float64
 25  changePercent         252 non-null    float64
dtypes: float64(17), int64(3), object(6)
memory usage: 53.2+ KB

In [4]:
df.columns

Index(['close', 'high', 'low', 'open', 'priceDate', 'symbol', 'volume', 'id',
       'key', 'subkey', 'updated', 'changeOverTime', 'marketChangeOverTime',
       'uOpen', 'uClose', 'uHigh', 'uLow', 'uVolume', 'fOpen', 'fClose',
       'fHigh', 'fLow', 'fVolume', 'label', 'change', 'changePercent'],
      dtype='object')